Rewind/Models/Comentarios.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Rewind.Models
{
    public class Comentarios
    {
        /// <summary>
        /// Chave primaria de ligação entre utilizadores e series
        /// </summary>
        [Key]
        public int ID { get; set; }
        /// <summary>
        /// FK do utilizador
        /// </summary>
        [ForeignKey(nameof(Utilizador))]
        [Display(Name = "Utilizador")]
        public int UtilizadoresID { get; set; }
        public Utilizadores Utilizador { get; set; }
        /// <summary>
        /// FK da Serie
        /// </summary>
        [ForeignKey(nameof(Serie))]
        [Display(Name = "Serie")]
        public int SeriesID { get; set; }
        public Series Serie { get; set; }
        /// <summary>
        /// Estado do comentario
        /// </summary>
        public string Estado { get; set; }
        /// <summary>
        /// Data de publicação do comentario
        /// </summary>
        public DateTime Data { get; set; }
        /// <summary>
        /// Comentario feito à serie por um utilizador
        /// </summary>
        public string Comentario { get; set; }
        /// <summary>
        /// Avaliação feita à serie por um utilizador
        /// </summary>
        [Range(1,5, ErrorMessage = "O valor das estrelas tem que ser entre {1} e {2}.")]
        [Required(ErrorMessage ="Adicione uma classificação")]
        [Display(Name ="Estrelas entre 1 e 5")]
        public int Estrelas { get; set; }
    }
}

Rewind/Controllers/SeriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rewind.Data;
using Rewind.Models;

namespace Rewind.Controllers
{
    public class SeriesController : Controller
    {
        /// <summary>
        /// representa a DB
        /// </summary>
        private readonly RewindDB _context;
        /// <summary>
        /// caminho para os dados web no server
        /// </summary>
        private readonly IWebHostEnvironment _caminho;
        /// <summary>
        /// esta variável recolhe os dados da pessoa q se autenticou
        /// </summary>
        private readonly UserManager<IdentityUser> _userManager;

        public SeriesController(RewindDB context, IWebHostEnvironment caminho, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _caminho = caminho;
            _userManager = userManager;
        }
        /// <summary>
        /// lista de todas as séries
        /// </summary>
        /// <returns></returns>
        // GET: Series
        public async Task<IActionResult> Index()
        {
            //vai buscar todos os estudios existentes para a view
            var rewindDB = _context.Series.Include(s => s.Estudio);
            return View(await rewindDB.ToListAsync());
        }
        /// <summary>
        /// envia para a view os detalhes da serie
        /// </summary>
        /// <param name="id">id da serie</param>
        /// <returns></returns>
        // GET: Series/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //verifica se o id enviado está a null
            if (id == null)
            {
                return NotFound();
            }
            //vai buscar a serie ao qual o id pertence
            var series = await _context.Series
                .Include(s => s.Estudio)
                .FirstOrDefaultAsync(m => m.ID == id);
            //verifica se existe essa série
            if (series == null)
            {
                return NotFound();
            }
            
            //ViewData["util"] = utilID.ID;
            return View(series);
        }
        /// <summary>
        /// criar as séries
        /// </summary>
        /// <returns></returns>
        // GET: Series/Create
        [Authorize(Roles = "Gestor")]
        public IActionResult Create()
        {
            //vai buscar todas os estudios que não estejam apagados e envia para a view
            ViewData["EstudioID"] = new SelectList(_context.Estudios.OrderBy(e=>e.Estudio).Where(e=>e.Estado!="apagado"), "ID", "Estudio");
            return View();
        }
        /// <summary>
        /// criador das series
        /// </summary>
        /// <param name="series">detalhes das series</param>
        /// <param name="imagemserie">ficheiro vindo da view</param>
        /// <returns></returns>
        // POST: Series/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Gestor")]
        public async Task<IActionResult> Create([Bind("ID,Titulo,Sinopse,Episodios,Estado,Ano,Imagem,Data,EstudioID")] Series series, IFormFile imagemserie)
        {
            //verificar se o utilizador escolheu um estudio
            if (series.EstudioID < 0)
            {
                ModelState.AddModelError("", "Por favor escolha um estudio");
                ViewData["EstudioID"] = new SelectList(_context.Estudios.Where(e=>e.Estado!="apagado"), "ID", "Estudio", series.EstudioID);
                return View(series);
            }
                //atribui o dia e a hora atual como dia de publicação.
                series.Data = DateTime.Now;
                string nomeImagem = "";
            //verificar se recebeu ficheiro
            if (imagemserie==null)
            {
                ModelState.AddModelError("", "Adicione uma fotografia da série.");
                ViewData["EstudioID"] = new SelectList(_context.Estudios.OrderBy(e => e.Estudio).Where(s => s.Estado != "apagado"), "ID", "Estudio");
                return View(series);
            }
            else
            {
                //verifica se é uma imagem jpg ou png
                if (imagemserie.ContentType == "image/jpeg" || imagemserie.ContentType == "image/png")
                {
                    //criar uma string para o nome da imagem não se repetir na pasta das fotos
                    Guid g;
                    g = Guid.NewGuid();
                    //coloca no nome da imagem com o titulo e com a string
                    nomeImagem = series.Titulo+"_"+g.ToString();
                    //extensão da imagem
                    string extensao = Path.GetExtension(imagemserie.FileName).ToLower();
                    //nome final do ficheiro
                    nomeImagem = nomeImagem + extensao;

                    //associar o nome da foto aos dados da BD
                    series.Imagem = nomeImagem;

                    //armazenamento da imagem
                    string localizacaoFicheiro = _caminho.WebRootPath;
                    nomeImagem = Path.Combine(localizacaoFicheiro, "fotos", nomeImagem);
                }
                else
                {
                    ModelState.AddModelError("", "Só pode escolher fotos");
                    ViewData["EstudioID"] = new SelectList(_context.Estudios.OrderBy(e => e.Estudio).Where(s => s.Estado != "apagado"), "ID", "Estudio");
                    return View(series);
                }
            }
            //se o modelo for valido
                if (ModelState.IsValid)
                {
                    try
                    {
                        //adiciona a serie
                        _context.Add(series);
                        //atualiza a base de dados
                        await _context.SaveChangesAsync();

                        //guardar no disco rigido do server a imagem
                        using var stream = new FileStream(nomeImagem,FileMode.Create);
                        await imagemserie.CopyToAsync(stream);

                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "Ocorreu um erro...");
                    }
                }
            
            
                ViewData["EstudioID"] = new SelectList(_context.Estudios, "ID", "Estudio", series.EstudioID);
                return View(series);
            
        }
        /// <summary>
        /// editar os dados da serie
        /// </summary>
        /// <param name="id">id da serie</param>
        /// <returns></returns>
        // GET: Series/Edit/5
        [Authorize(Roles = "Gestor")]
        public async Task<IActionResult> Edit(int? id)
        {
            //verifica se o id da serie é null
            if (id == null)
            {
                return NotFound();
            }
            //vai buscar os dados da serie
            var series = await _context.Series.FindAsync(id);
            if (series == null)
            {
                return NotFound();
            }
            //vai buscar os dados dos estudios para enviar para a view onde o estudio não foi apagado
            ViewData["EstudioID"] = new SelectList(_context.Estudios.Where(s => s.Estado != "apagado"), "ID", "Estudio", series.EstudioID);
            //guarda numa variavel de sessão o id da serie para verificar se o utilizador não tenta fazer batota
            HttpContext.Session.SetInt32("IDSerieEdicao",series.ID);
            return View(series);
        }
        /// <summary>
        /// editar a serie
        /// </summary>
        /// <param name="id">id da serie</param>
        /// <param name="series">dados da serie</param>
        /// <param name="imagemserie">ficheiro vindo da view</param>
        /// <returns></returns>
        // POST: Series/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Gestor")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Titulo,Sinopse,Episodios,Estado,Ano,Imagem,Data,EstudioID")] Series series, IFormFile imagemserie)
        {
            //se o id for diferente do id da serie
            if (id != series.ID)
            {
                return NotFound();
            }
            //verifica a variavel de sessão do id da serie para verificar se o utilizador não tenta fazer batota
            var IDSerieEdit = HttpContext.Session.GetInt32("IDSerieEdicao");

            if (IDSerieEdit == null || IDSerieEdit!=series.ID)
            {
                return RedirectToAction("Index");
            }

            string nomeImagem = "";
            if (imagemserie != null)
            {
                if (imagemserie.ContentType == "image/jpeg" || imagemserie.ContentType == "image/png")
                {
                    //criar uma string para o nome da imagem não se repetir na pasta das fotos
                    Guid g;
                    g = Guid.NewGuid();
                    //coloca no nome da imagem com o titulo e com a string
                    nomeImagem = series.Titulo + "_" + g.ToString();
                    //extensão da imagem
                    string extensao = Path.GetExtension(imagemserie.FileName).ToLower();

Rewind/Views/Comentarios/Create.cshtml
@model Rewind.Models.Comentarios

@{
    ViewData["Title"] = "Criar";
}

<h1>Criar</h1>

<h4>Comentarios</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div hidden class="form-group">
                <label asp-for="UtilizadoresID" class="control-label"></label>
                <select asp-for="UtilizadoresID" class ="form-control" asp-items="ViewBag.UtilizadoresID"></select>
            </div>
            <div hidden class="form-group">
                <label asp-for="SeriesID" class="control-label"></label>
                <input asp-for="SeriesID" class ="form-control" type="text" value="@ViewBag.id" readonly>
            </div>
            <div hidden class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            @*<div hidden class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Comentario" class="control-label"></label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estrelas" class="control-label"></label>
                <input asp-for="Estrelas" class="form-control" />
                <span asp-validation-for="Estrelas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="Series" asp-route-id="@ViewBag.id">Voltar a série</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rewind/Views/Comentarios/Delete.cshtml
@model Rewind.Models.Comentarios

@{
    ViewData["Title"] = "Apagar";
}

<h1>Delete</h1>

<h3>Tem a certeza que quer apagar?</h3>
<div>
    <h4>Comentarios</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Utilizador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Utilizador.Email)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Serie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Serie.Titulo)
        </dd class>
        <dt hidden class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd hidden class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comentario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estrelas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estrelas)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-route-id="@Model.Serie.ID">Voltar aos comentários</a>
    </form>
</div>

Rewind/Views/Comentarios/Details.cshtml
@model Rewind.Models.Comentarios

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Comentarios</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Utilizador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Utilizador.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Serie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Serie.Titulo)
        </dd>
        <dt hidden class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd hidden class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comentario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estrelas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estrelas)
        </dd>
    </dl>
</div>
<div>
    @*verifica se o comentario pertence ao utilizador autenticado*@
    @if (ViewBag.util == Model.UtilizadoresID && User.Identity.IsAuthenticated)
    {
        <text>
        <a asp-action="Edit" asp-route-id="@Model.ID">Editar</a>|
        </text>
    }
    <a asp-action="Index" asp-route-id="@Model.Serie.ID">Voltar aos comentários</a>
            </div>

Rewind/Views/Comentarios/Edit.cshtml
@model Rewind.Models.Comentarios

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Comentarios</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div hidden class="form-group">
                <label asp-for="UtilizadoresID" class="control-label"></label>
                <select asp-for="UtilizadoresID" class="form-control" asp-items="ViewBag.UtilizadoresID"></select>
                <span asp-validation-for="UtilizadoresID" class="text-danger"></span>
            </div>
            <div hidden class="form-group">
                <label asp-for="SeriesID" class="control-label"></label>
                <select asp-for="SeriesID" class="form-control" asp-items="ViewBag.SeriesID"></select>
                <span asp-validation-for="SeriesID" class="text-danger"></span>
            </div>
            <div hidden class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Comentario" class="control-label"></label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estrelas" class="control-label"></label>
                <input asp-for="Estrelas" class="form-control" />
                <span asp-validation-for="Estrelas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@Model.Serie.ID">Voltar aos comentários</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rewind/Views/Comentarios/Index.cshtml
@model IEnumerable<Rewind.Models.Comentarios>

@{
    ViewData["Title"] = "Comentarios";
}

<h1>Lista de Comentarios</h1>

<p>
@*É verificado se o utilizador autenticado ja comentou esta série*@
@if (User.Identity.IsAuthenticated && ViewBag.ex == "nexiste")
{
<a asp-action="Create" asp-controller="Comentarios" asp-route-id="@ViewBag.serie">Adicionar um comentário</a><br />
}
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Utilizador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Serie)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comentario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estrelas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Utilizador.Utilizador)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.Titulo)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comentario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estrelas)
        </td>
        <td>
            @*Verifica se este comentario pertence ao utilizador autenticado*@
            @if (ViewBag.util == item.UtilizadoresID && User.Identity.IsAuthenticated)
            {
        <text>
            <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
        </text>}
            <a asp-action="Details" asp-route-id="@item.ID">Detalhes</a>
            @*Verifica se este comentario pertence ao utilizador autenticado*@
            @if (ViewBag.util == item.UtilizadoresID && User.Identity.IsAuthenticated)
            {
        <text>
            |<a asp-action="Delete" asp-route-id="@item.ID">Apagar</a>
        </text>}
        </td>
    </tr>
    }
    </tbody>
</table>